import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { catalog, SECRET_STORE_LABELS, REQUIRED_PG_EXTENSIONS } from "./catalog.js";
import { serverEnvSchema } from "./env.js";
import { publicEnvSchema } from "./public.js";

/**
 * Emits .env.example and ops/CATALOG.md from the catalogue declarations.
 *
 * Both are generated rather than hand-maintained so they cannot drift from the
 * code, which is what happened to every piece of v1's configuration docs.
 *
 * CATALOG.md goes in ops/ rather than docs/ because .github/workflows/
 * github-pages.yml uploads docs/ wholesale to GitHub Pages, which would publish
 * the dependency inventory as a live web page.
 */

const here = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(here, "../../..");

function defaultFor(name: string): string | undefined {
  const shape = {
    ...serverEnvSchema.shape,
    ...publicEnvSchema.shape,
  } as Record<string, { safeParse: (v: unknown) => { success: boolean; data?: unknown } }>;
  const field = shape[name];
  if (!field) return undefined;
  const parsed = field.safeParse(undefined);
  return parsed.success && parsed.data !== undefined ? String(parsed.data) : undefined;
}

function renderEnvExample(): string {
  const lines: string[] = [
    "# Generated by `npm run generate --workspace @lunchmeet/config`.",
    "# Do not edit by hand: regenerate from packages/config/src/catalog.ts.",
    "#",
    "# Copy to .env and fill in. Values shown are development defaults; the API",
    "# boots with an empty .env against the local docker compose stack.",
    "",
  ];

  for (const entry of catalog) {
    lines.push(`# ${"-".repeat(70)}`);
    lines.push(`# ${entry.title}${entry.critical ? "" : " (optional)"}`);
    lines.push(`# ${entry.purpose}`);
    if (entry.obtain) lines.push(`# Obtain: ${entry.obtain}`);
    lines.push(`# ${"-".repeat(70)}`);

    for (const spec of entry.env) {
      if (spec.note) lines.push(`# ${spec.note}`);
      const marker = spec.secret ? " (secret)" : "";
      const requirement = spec.required ? "required" : "optional";
      lines.push(`# ${requirement}${marker} -> ${SECRET_STORE_LABELS[spec.store]}`);
      const value = defaultFor(spec.name);
      lines.push(`${spec.name}=${value ?? ""}`);
      lines.push("");
    }
  }

  lines.push("# " + "-".repeat(70));
  lines.push("# Public configuration (safe to ship in the mobile bundle)");
  lines.push("# " + "-".repeat(70));
  for (const name of Object.keys(publicEnvSchema.shape)) {
    lines.push(`${name}=${defaultFor(name) ?? ""}`);
  }
  lines.push("");

  return lines.join("\n");
}

function renderCatalogDoc(): string {
  const lines: string[] = [
    "# Dependency Catalogue",
    "",
    "Generated from `packages/config/src/catalog.ts`. Do not edit by hand.",
    "",
    "Every external system LunchMeet talks to, what it is for, and what it needs",
    "to be configured. Run `npm run doctor` to check which are reachable.",
    "",
    "Credential provisioning instructions live in [PRODUCTION_SECRETS.md](PRODUCTION_SECRETS.md).",
    "",
  ];

  for (const entry of catalog) {
    lines.push(`## ${entry.title}${entry.critical ? "" : " (optional)"}`);
    lines.push("");
    lines.push(entry.purpose);
    lines.push("");
    if (entry.obtain) {
      lines.push(`**Obtain:** ${entry.obtain}`);
      lines.push("");
    }
    if (entry.postgresExtensions?.length) {
      lines.push(
        `**Required Postgres extensions:** ${entry.postgresExtensions
          .map((e) => `\`${e}\``)
          .join(", ")}`
      );
      lines.push("");
    }

    if (entry.env.length > 0) {
      lines.push("| Variable | Required | Secret | Stored in |");
      lines.push("|---|---|---|---|");
      for (const spec of entry.env) {
        lines.push(
          `| \`${spec.name}\` | ${spec.required ? "yes" : "no"} | ${
            spec.secret ? "yes" : "no"
          } | ${SECRET_STORE_LABELS[spec.store]} |`
        );
      }
      lines.push("");
      const notes = entry.env.filter((s) => s.note);
      if (notes.length > 0) {
        for (const spec of notes) {
          lines.push(`- \`${spec.name}\`: ${spec.note}`);
        }
        lines.push("");
      }
    }
  }

  lines.push("## Production database prerequisites");
  lines.push("");
  lines.push(
    "Migrations issue `CREATE EXTENSION`, which a non-superuser role cannot do. An"
  );
  lines.push(
    "administrator must pre-create these in the production database or the first"
  );
  lines.push("deploy fails:");
  lines.push("");
  for (const ext of REQUIRED_PG_EXTENSIONS) {
    lines.push(`- \`${ext}\``);
  }
  lines.push("");

  return lines.join("\n");
}

function main(): void {
  const envExamplePath = path.join(repoRoot, ".env.example");
  writeFileSync(envExamplePath, renderEnvExample(), "utf8");

  const opsDir = path.join(repoRoot, "ops");
  mkdirSync(opsDir, { recursive: true });
  const catalogDocPath = path.join(opsDir, "CATALOG.md");
  writeFileSync(catalogDocPath, renderCatalogDoc(), "utf8");

  console.log(`Wrote ${path.relative(repoRoot, envExamplePath)}`);
  console.log(`Wrote ${path.relative(repoRoot, catalogDocPath)}`);
}

main();
